language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "pypy3"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse unittest2; fi
    - python setup.py install

script:
    -  nosetests --with-coverage --cover-package=alpha_vantage

after_success:
    - pip install --quiet coveralls
    - coveralls
